### ISSUE TITLE
Диалоги

### ISSUE THREAD

**Issue by delevelme** [molotoksoftware/auction#12]
Ребята привет! Считаю очень важным моментом реализацию диалогов. Чтобы продавец мог написать покупателю или наоборот. Если кто-то уже начал делать этот функционал просьба поделиться наработками.

**Comment by komunalrf** [comment]
Думаю для аукционов это излишняя мера. По опыту работы с ebay знаю. Не удобно. Просто нужно чуть удобнее реализовать работу с общением через e-mail, сделать форму для отправки сообщений прямо с сайта. Вот и всё. Это же не социальная сеть. Вконтакте вы не замените. А потому сообщения как и во многих других сервисах не будут использованы в полной мере. Если у покупателя есть вопрос, он или напишет или позвонит.
