### ISSUE TITLE
В демке не реализовано пополнение счета вообще

### ISSUE THREAD

**Issue by Olden** [molotoksoftware/auction#13]
в коде отсутсвуют как минимум вьюхи.

Этот функционал не реализован?

**Comment by molotoksoftware** [comment]
Пополнение счета через что?

Вы ведь понимаете что для пополнения счета нужен функционал для работы с агрегатором.

**Comment by molotoksoftware** [comment]
К выходу 1.0 возможно добавим в базу один агрегатор, например робокассу

**Comment by Olden** [comment]
прочитав ваш лэндинг не увидел что это еще не релизная версия, спасибо. а какие ближайшие планы по функционалу и прогнозы по выпуску 1.0?

**Comment by molotoksoftware** [comment]
Полноценная поддержка локализации - основной критерий для выхода 1.0

**Comment by komunalrf** [comment]
Правильно ли я понимаю, что ячейка status в таблице sales в текущей версии скрипта не задействована? Какие значения предполагаете использовать для нее? Думаю воспользоваться ей для проставления статусов: ожидает оплаты, оплачен, комплектуется, отправлен, доставлен. Если заранее подскажите какие цифровые значения для них планируете использовать, буду благодарен.

**Comment by molotoksoftware** [comment]
Да, верно, предполагается использование этой колонки именно для этих целей. Цифровые значения скорее всего будут в константах.

**Comment by goldwizard13** [comment]
Здравствуйте, когда выйдет версия 1.0, и как будет можно обновить версию 0.9 до 1.0, спасибо
