### ISSUE TITLE
IIS installation issue

### ISSUE THREAD

**Issue by taufa** [molotoksoftware/auction#16]
Sorry Im a rookie I migrated to IIS but cannot view admin page on backend. Its showing HTTP Error 404.0 - Not Found sending request to a folder that doesnt exist.
Requested URL	   http://admin.auction.local:80/admin/admin/login
The same goes when clicking an auction in frontend - Requested URL	   http://auction.local:80/auction/
Am I missing something? Please help, hope to hear from you soon

Regards

**Comment by ghost** [comment]
brokeaf
