### ISSUE TITLE
Извиняюсь за вопрос ! 

### ISSUE THREAD

**Issue by Devalenok** [molotoksoftware/auction#17]
Как зайти то в админку ?

**Comment by komunalrf** [comment]
админка доступна по отдельному url адресу, который вы должны были создать

**Comment by Devalenok** [comment]
А можно поподробней, создал URL admin.on-wall.ru но это же пустая папка, вот не могу понять как попасть в админ папку. А так ошибка http://on-wall.ru/backend
Заранее спасибо за помощь !

**Comment by Devalenok** [comment]
Тему можно закрыть, разобрался !
