### ISSUE TITLE
В чем может быть причина ?

### ISSUE THREAD

**Issue by Devalenok** [molotoksoftware/auction#18]
![2017-04-18 21 40 23](https://cloud.githubusercontent.com/assets/11627014/25144674/bd6b3d6c-247f-11e7-9d1d-2ed442841536.png)

**Comment by komunalrf** [comment]
настройки php

**Comment by komunalrf** [comment]
PHP также допускает короткий открывающий тег <?, они доступны только если включены с помощью конфигурационной директивы php.ini short_open_tag, либо если PHP был сконфигурирован с опцией --enable-short-tags .

**Comment by Devalenok** [comment]
Спасибо большое, это помогло.
