### ISSUE TITLE
Не работает кнопка изменения баланса пользователя в админке

### ISSUE THREAD

**Issue by fredy314** [molotoksoftware/auction#2]
Такое ощущение что какие-то скрипты или не подключены или не сработали
http://joxi.ru/Grq1gndfNLeKGr
Кнопка как видно на скрине вроде присутствует но почему-то скрыта,  и если ее просто открыть она не работает никак вообще

**Comment by molotoksoftware** [comment]
d3aea152b85b01ec95a4e0657c7cc2b616a1c2fb
