### ISSUE TITLE
Base URL configuration

### ISSUE THREAD

**Issue by igy-christophe** [molotoksoftware/auction#29]
Hello,

We installed **auction** inside the www directory, without using VirtualHost.
So is there any way to configure the Base URL ?
If yes, how ?

Here is a screenshot of some unfound resources.

![Screen Shot 2020-06-30 at 17 21 28](https://user-images.githubusercontent.com/65895221/86137813-5a6c7580-baf6-11ea-86e4-fa203b2b91cc.png)

Many thanks.

**Comment by molotoksoftware** [comment]
Hello!
without using VirtualHost -  bad idea. Many things in this project depends from server. I have no idea how to get that you want.
May be the link on [yii docs](https://www.yiiframework.com/doc/guide/1.1/en) help you? [Installation](https://www.yiiframework.com/doc/guide/1.1/en/quickstart.installation)
