### ISSUE TITLE
В разделе "История пополнений" выводится только пополнения баланса Снятия с баланса и Другие доступные варианты не выводятся никуда вообще.

### ISSUE THREAD

**Issue by fredy314** [molotoksoftware/auction#6]
Снятия с баланса (при редактировании через админку)
и Другие доступные в модели BalanceHistory варианты
не выводятся никуда вообще.
Предлагаю вывести в тот-же список, только указав тип записи (пополнение/снятие/возврат/коммиссия/реферальные)  ну и для снятий/коммисий сумму с минусом писать.

**Comment by molotoksoftware** [comment]
http://joxi.ru/BA09E1bHB5we6r

**Comment by fredy314** [comment]
Это на фронтенде а в админке прописано только :type' => BalanceHistory::STATUS_ADD
