### ISSUE TITLE
Предлагаю на странице со списком пользователей /user/user/index вывести значение баланса пользователя можно со ссылкой на его историю

### ISSUE THREAD

**Issue by fredy314** [molotoksoftware/auction#8]

**Comment by komunalrf** [comment]
Зачем? Бессмыслица какая-то. Отзывы и рейтинг - единственные важные в этом смысле вещи.

**Comment by fredy314** [comment]
Баланс и вдруг не важен?

**Comment by komunalrf** [comment]
Прошу прощения. Думал речь идет о публичной странице (которую не нашел). В админке, да. Имеет смысл. =)
